#signup
POST http://localhost:3001/users/signup/
Content-Type: application/json

{
    "firstname":"joseph",
    "lastname":"boby",
    "username":"joe",
    "password":"test"
}
###
# @name login
POST http://localhost:3001/users/login/
Content-Type: application/json

{
    "username":"joe",
    "password":"test"
}
> {%
client.global.set('authToken', response.body.token);
%}
###
#addDish
POST http://localhost:3001/dishes/
Content-Type: application/json
Authorization: bearer {{authToken}}

{
    "name":"Uthappizza",
    "image": "/images/uthapizza.jpg",
    "category": "mains",
    "label":"Hot",
    "price":"4.99",
    "featured": true,
    "description":"A unique combination of Indian Uthappam (pancake) and Italian pizza, topped with Cerignola olives, ripe vine cherry tomatoes, Vidalia onion, Guntur chillies and Buffalo Paneer."
}
###
#addDish
POST http://localhost:3001/dishes/
Content-Type: application/json
Authorization: bearer {{authToken}}

{
    "name":"Zucchipakoda",
    "image": "/images/zucchipakoda.png",
    "category": "appetizer",
    "label":"",
    "price":"1.99",
    "featured": false,
    "description":"Deep fried Zucchini coated with mildly spiced Chickpea flour batter accompanied with a sweet-tangy tamarind sauce"
}
###
#addDish
POST http://localhost:3001/dishes/
Content-Type: application/json
Authorization: bearer {{authToken}}

{
    "name":"Vadonut",
    "image": "/images/vadonut.png",
    "category": "appetizer",
    "label":"New",
    "price":"1.99",
    "featured": false,
    "description":"A quintessential Di Udupi experience, is it a vada or is it a donut?"
}
###
#addDish
POST http://localhost:3001/dishes/
Content-Type: application/json
Authorization: bearer {{authToken}}

{
    "name":"ElaiCheese Cake",
    "image": "/images/elaicheesecake.png",
    "category": "dessert",
    "label":"",
    "price":"2.99",
    "featured": false,
    "description":"A delectable, semi-sweet New York Style Cheese Cake, with Graham cracker crust and spiced with Indian cardamoms"
}
###
#addLeader
POST http://localhost:3001/leaders/
Content-Type: application/json
Authorization: bearer {{authToken}}

{
    "name": "Peter Pan",
    "image": "/images/alberto.png",
    "designation": "Chief Epicurious Officer",
    "abbr": "CEO",
    "featured": false,
    "description": "Our CEO, Peter, credits his hardworking East Asian immigrant parents who undertook the arduous journey to the shores of America with the intention of giving their children the best future. His mother's wizardy in the kitchen whipping up the tastiest dishes with whatever is available inexpensively at the supermarket, was his first inspiration to create the fusion cuisines for which The Frying Pan became well known. He brings his zeal for fusion cuisines to this restaurant, pioneering cross-cultural culinary connections."
}
###
#addLeader
POST http://localhost:3001/leaders/
Content-Type: application/json
Authorization: bearer {{authToken}}

{
    "name": "Dhanasekaran Witherspoon",
    "image": "/images/alberto.png",
    "designation": "Chief Food Officer",
    "abbr": "CFO",
    "featured": false,
    "description": "Our CFO, Danny, as he is affectionately referred to by his colleagues, comes from a long established family tradition in farming and produce. His experiences growing up on a farm in the Australian outback gave him great appreciation for varieties of food sources. As he puts it in his own words, Everything that runs, wins, and everything that stays, pays!"
}
###
#addLeader
POST http://localhost:3001/leaders/
Content-Type: application/json
Authorization: bearer {{authToken}}

{
    "name": "Alberto Somayya",
    "image": "/images/alberto.png",
    "designation": "Executive Chef",
    "abbr": "EC",
    "featured": true,
    "description": "Award winning three-star Michelin chef with wide International experience having worked closely with whos-who in the culinary world, he specializes in creating mouthwatering Indo-Italian fusion experiences. He says, Put together the cuisines from the two craziest cultures, and you get a winning hit! Amma Mia!"
}

###
#addPromotion
POST http://localhost:3001/promotions
Content-Type: application/json
Authorization: bearer {{authToken}}

{
  "name": "Weekend Grand Buffet",
  "image": "/images/weekendgrandbuffet.jpg",
  "label": "New",
  "price": "19.99",
  "featured": true,
  "description": "Featuring mouthwatering combinations with a choice of five different salads, six enticing appetizers, six main entrees and five choicest desserts. Free flowing bubbly and soft drinks. All for just $19.99 per person"

}
